# Generated by Django 3.0.5 on 2020-05-24 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20200524_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='records',
        ),
    ]
