# Generated by Django 3.0.5 on 2020-05-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20200524_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='salary',
        ),
    ]
