# Generated by Django 3.0.5 on 2020-05-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_reciept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciept',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
